#!/usr/bin/env bash
# Wrapper regenerated by start-miner.sh; placeholder for manual use
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
set -a
[[ -f "$ROOT/.env" ]] && source "$ROOT/.env"
set +a
MIID_DIR="$ROOT/MIID-subnet"
VENV="$MIID_DIR/miner_env"
export PYTHONUNBUFFERED=1
export GENERATE_API_URL="${GENERATE_API_URL:-https://chatgpt-api-1.vercel.app/api/generate}"
export MIID_SAVE_DIR="$MIID_DIR/hasil_final_qc"
export MIID_REPORT_DIR="$MIID_DIR/laporan_tugas"
export PATH="$VENV/bin:$ROOT/bin:$PATH"
exec "$VENV/bin/python" "$MIID_DIR/neurons/miner.py" \
  --netuid "${NETUID:-54}" \
  --subtensor.network "${SUBTENSOR_NETWORK:-finney}" \
  --subtensor.chain_endpoint "${SUBTENSOR_ENDPOINT:-wss://entrypoint-finney.opentensor.ai:443}" \
  --wallet.name "${WALLET_NAME:-wallet_mainnet}" \
  --wallet.hotkey "${WALLET_HOTKEY:-default}" \
  --axon.port "${AXON_PORT:-1080}" \
  --axon.ip "${AXON_IP:-0.0.0.0}" \
  --axon.external_ip "${AXON_EXTERNAL_IP}" \
  --axon.external_port "${AXON_EXTERNAL_PORT}" \
  --priority.max_workers "${PRIORITY_MAX_WORKERS:-50}" \
  --axon.max_workers "${AXON_MAX_WORKERS:-50}" \
  --logging.debug
