#!/usr/bin/env bash
# Wrapper regenerated by start-miner.sh; placeholder for manual use
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
set -a
[[ -f "$ROOT/.env" ]] && source "$ROOT/.env"
set +a
export PATH="$ROOT/bin:$PATH"
exec "$ROOT/bin/localtonet" --authtoken "${LOCALTONET_AUTHTOKEN}"
